import React, { useEffect, useMemo, useState } from "react";

const CLIENT_KEY="masfertil_clientes_v1", ORDER_KEY="masfertil_pedidos_v1", NEXT_KEY="masfertil_numero_v1", DRAFT_KEY="masfertil_nota_borrador_v1";
const blank=()=>({cantidad:"",unidad:"",descripcion:"",precio:""});
const emptyClient={ruc:"",nombre:"",area:"",direccion:"",region:"",telefono:"",correo:"",ciudad:""};
const money=v=>Number(v||0).toLocaleString("es-PY",{minimumFractionDigits:2,maximumFractionDigits:2});
const fmtDate=v=>v?new Date(`${v}T00:00:00`).toLocaleDateString("es-PY"):"";
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function key(v){return String(v||"").trim().replace(/\s/g,"")}
function loadDraft(){return load(DRAFT_KEY,null)}

const UNIDADES=["CERO","UNO","DOS","TRES","CUATRO","CINCO","SEIS","SIETE","OCHO","NUEVE"];
const DIEZ_DIECINUEVE=["DIEZ","ONCE","DOCE","TRECE","CATORCE","QUINCE","DIECISÉIS","DIECISIETE","DIECIOCHO","DIECINUEVE"];
const DECENAS=["","","VEINTE","TREINTA","CUARENTA","CINCUENTA","SESENTA","SETENTA","OCHENTA","NOVENTA"];
const CENTENAS=["","CIENTO","DOSCIENTOS","TRESCIENTOS","CUATROCIENTOS","QUINIENTOS","SEISCIENTOS","SETECIENTOS","OCHOCIENTOS","NOVECIENTOS"];
function grupo(n){n=Number(n);if(n===0)return "";if(n<10)return UNIDADES[n];if(n<20)return DIEZ_DIECINUEVE[n-10];if(n<30)return n===20?"VEINTE":"VEINTI"+UNIDADES[n-20].toLowerCase().toUpperCase();if(n<100)return DECENAS[Math.floor(n/10)]+(n%10?" Y "+UNIDADES[n%10]:"");if(n<200)return n===100?"CIEN":"CIENTO "+grupo(n-100);return CENTENAS[Math.floor(n/100)]+(n%100?" "+grupo(n%100):"")}
function numeroLetras(n){n=Math.floor(Number(n||0));if(n===0)return "CERO";if(n<1000)return grupo(n);if(n<1000000){const miles=Math.floor(n/1000),resto=n%1000;return (miles===1?"MIL":grupo(miles)+" MIL")+(resto?" "+grupo(resto):"")}if(n<1000000000){const millones=Math.floor(n/1000000),resto=n%1000000;return (millones===1?"UN MILLÓN":grupo(millones)+" MILLONES")+(resto?" "+numeroLetras(resto):"")}const milesMillones=Math.floor(n/1000000000),resto=n%1000000000;return (milesMillones===1?"MIL MILLONES":numeroLetras(milesMillones)+" MIL MILLONES")+(resto?" "+numeroLetras(resto):"")}
function words(n,currency){const value=Math.max(0,Number(n||0)),entero=Math.floor(value+0.000001),centavos=Math.round((value-entero)*100);const unit=currency==="USD"?"DÓLARES AMERICANOS":"GUARANÍES";let text=`${numeroLetras(entero)} ${unit}`;if(centavos>0)text+=` CON ${numeroLetras(centavos)} CENTAVOS`;return text}

export default function App(){
 const draft=loadDraft()||{};
 const [number,setNumber]=useState(()=>draft.number??Math.max(51,Number(localStorage.getItem(NEXT_KEY)||51)));
 const [date,setDate]=useState(()=>draft.date??new Date().toISOString().slice(0,10)),[type,setType]=useState(()=>draft.type??"PEDIDO");
 const [currency,setCurrency]=useState(()=>draft.currency??"PYG");
 const [client,setClient]=useState(()=>draft.client??emptyClient),[query,setQuery]=useState(()=>draft.query??"");
 const [items,setItems]=useState(()=>draft.items??Array.from({length:10},blank)),[obs,setObs]=useState(()=>draft.obs??"");
 const [contado,setContado]=useState(()=>!!draft.contado),[plazo,setPlazo]=useState(()=>!!draft.plazo),[semilla,setSemilla]=useState(()=>!!draft.semilla),[venc,setVenc]=useState(()=>draft.venc??""),[flete,setFlete]=useState(()=>draft.flete??"");
 const [msg,setMsg]=useState(""),[history,setHistory]=useState([]),[showHistory,setShowHistory]=useState(false),[showCancel,setShowCancel]=useState(false),[cancelReason,setCancelReason]=useState("");
 const [status,setStatus]=useState(()=>draft.status??"VIGENTE");
 const [isSaved,setIsSaved]=useState(()=>!!draft.isSaved),[editMode,setEditMode]=useState(()=>!!draft.editMode);
 const total=useMemo(()=>items.reduce((s,i)=>s+Number(i.cantidad||0)*Number(i.precio||0),0),[items]);
 const obsLines=Math.min(4,Math.max(1,Math.ceil(Math.max(1,obs.length)/90)+Math.max(0,(obs.match(/\n/g)||[]).length)));
 const obsHeight=`${8+obsLines*3}mm`;
 const symbol=currency==="USD"?"US$":"Gs.";
 const currencyLabel=currency==="USD"?"DÓLARES AMERICANOS":"GUARANÍES";
 const setC=(k,v)=>setClient(c=>({...c,[k]:v}));
 const update=(i,k,v)=>setItems(a=>a.map((x,j)=>j===i?{...x,[k]:v}:x));
 const draftData=()=>({number,date,type,currency,client,query,items,obs,contado,plazo,semilla,venc,flete,status,isSaved,editMode});
 function resetHistory(){setHistory([]);setShowHistory(false)}
 useEffect(()=>{try{localStorage.setItem(DRAFT_KEY,JSON.stringify(draftData()))}catch{}},[number,date,type,currency,client,query,items,obs,contado,plazo,semilla,venc,flete,status,isSaved,editMode]);
 useEffect(()=>{const keep=()=>{try{localStorage.setItem(DRAFT_KEY,JSON.stringify(draftData()))}catch{}};window.addEventListener("pagehide",keep);document.addEventListener("visibilitychange",keep);return()=>{window.removeEventListener("pagehide",keep);document.removeEventListener("visibilitychange",keep)}},[number,date,type,currency,client,query,items,obs,contado,plazo,semilla,venc,flete,status,isSaved,editMode]);
 function buscar(){const k=key(query),clients=load(CLIENT_KEY,{}),orders=load(ORDER_KEY,[]);if(!k){setMsg("Ingrese RUC/C.I.");return}if(clients[k]){setClient(clients[k]);setMsg("Cliente encontrado.")}else{setClient({...emptyClient,ruc:query});setMsg("Cliente no encontrado. Puede registrarlo.")}const h=orders.filter(o=>key(o.client?.ruc)===k).sort((a,b)=>Number(b.number)-Number(a.number));setHistory(h);setShowHistory(h.length>0)}
 function saveClient(){if(!client.ruc.trim())return setMsg("Ingrese RUC/C.I.");const c=load(CLIENT_KEY,{});c[key(client.ruc)]=client;localStorage.setItem(CLIENT_KEY,JSON.stringify(c));setMsg("Cliente guardado.")}
 function startEdit(){if(!isSaved)return setMsg("La nota todavía no fue guardada.");if(status==="ANULADA")return setMsg("Una nota anulada no puede modificarse.");setEditMode(true);setMsg(`Modo MODIFICAR activado para la nota N° ${String(number).padStart(6,"0")}.`)}
 function save(){if(status==="ANULADA")return setMsg("Esta nota está anulada y no puede modificarse.");if(isSaved&&!editMode)return setMsg("Presione MODIFICAR antes de cambiar esta nota.");if(!client.ruc.trim())return setMsg("Ingrese RUC/C.I.");const o=load(ORDER_KEY,[]),now=new Date().toISOString(),existing=o.findIndex(x=>Number(x.number)===Number(number));const previous=existing>=0?o[existing]:null;const record={number,date,type,currency,client:{...client},items:items.filter(i=>i.cantidad||i.unidad||i.descripcion||i.precio),total,obs,contado,plazo,semilla,venc,flete,status:"VIGENTE",createdAt:previous?.createdAt||now,modifiedAt:previous?now:undefined,modificationCount:Number(previous?.modificationCount||0)+(previous?1:0)};if(existing>=0)o[existing]=record;else o.push(record);localStorage.setItem(ORDER_KEY,JSON.stringify(o));const c=load(CLIENT_KEY,{});c[key(client.ruc)]=client;localStorage.setItem(CLIENT_KEY,JSON.stringify(c));if(existing<0){const next=Math.max(Number(number)+1,Number(localStorage.getItem(NEXT_KEY)||51));localStorage.setItem(NEXT_KEY,next);setNumber(next)}setIsSaved(true);setEditMode(false);localStorage.removeItem(DRAFT_KEY);setMsg(existing>=0?`Modificada y guardada N° ${String(number).padStart(6,"0")}.`:`Guardada N° ${String(number).padStart(6,"0")}.`)}
 function loadOrder(o){setNumber(Number(o.number));setDate(o.date||"");setType(o.type||"PEDIDO");setCurrency(o.currency||"PYG");setClient(o.client||emptyClient);setQuery(o.client?.ruc||"");setItems([...((o.items||[])),...Array.from({length:Math.max(0,10-(o.items||[]).length)},blank)].slice(0,10));setObs(o.obs||"");setContado(!!o.contado);setPlazo(!!o.plazo);setSemilla(!!o.semilla);setVenc(o.venc||"");setFlete(o.flete||"");setStatus(o.status||"VIGENTE");setIsSaved(true);setEditMode(false);setShowHistory(false);setMsg(`Nota N° ${String(o.number).padStart(6,"0")} cargada. Presione MODIFICAR para actualizarla.`)}
 function cancelOrder(){if(status==="ANULADA")return setMsg("La nota ya está anulada.");if(!cancelReason.trim())return setMsg("Debe indicar el justificativo de la anulación.");const o=load(ORDER_KEY,[]),idx=o.findIndex(x=>Number(x.number)===Number(number));if(idx<0)return setMsg("Primero guarde la nota para poder anularla.");o[idx]={...o[idx],status:"ANULADA",cancelReason:cancelReason.trim(),cancelledAt:new Date().toISOString()};localStorage.setItem(ORDER_KEY,JSON.stringify(o));setStatus("ANULADA");setIsSaved(true);setEditMode(false);setShowCancel(false);setCancelReason("");setMsg(`N° ${String(number).padStart(6,"0")} ANULADA y registrada en el historial.`);const h=o.filter(x=>key(x.client?.ruc)===key(client.ruc)).sort((a,b)=>Number(b.number)-Number(a.number));setHistory(h);setShowHistory(true)}
 function nuevo(){localStorage.removeItem(DRAFT_KEY);setNumber(Math.max(51,Number(localStorage.getItem(NEXT_KEY)||51)));setDate(new Date().toISOString().slice(0,10));setType("PEDIDO");setCurrency("PYG");setClient(emptyClient);setQuery("");setItems(Array.from({length:10},blank));setObs("");setContado(false);setPlazo(false);setSemilla(false);setVenc("");setFlete("");setStatus("VIGENTE");setIsSaved(false);setEditMode(true);setMsg("");setHistory([]);setShowHistory(false);setShowCancel(false)}
 const locked=status==="ANULADA"||(isSaved&&!editMode);
 return <div className="app">
  <div className="toolbar no-print"><button onClick={save}>GUARDAR NOTA</button><button onClick={saveClient}>GUARDAR CLIENTE</button><button onClick={startEdit} disabled={!isSaved||status==="ANULADA"}>MODIFICAR</button><button className="danger" onClick={()=>setShowCancel(true)}>ANULAR</button><button onClick={()=>window.print()}>IMPRIMIR</button><button onClick={nuevo}>NUEVA NOTA</button><label className="currency-selector"><b>MONEDA:</b><select value={currency} disabled={locked} onChange={e=>setCurrency(e.target.value)}><option value="PYG">GUARANÍES (Gs.)</option><option value="USD">DÓLARES (US$)</option></select></label><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Consultar RUC/C.I."/><button onClick={buscar}>BUSCAR</button></div>{msg&&<span>{msg}</span>}</div>
  {showCancel&&<div className="modal no-print"><div className="modal-card"><h3>Anular Nota de Pedido N° {String(number).padStart(6,"0")}</h3><p>La anulación no elimina la hoja ni reutiliza el número. Quedará registrada en el historial del cliente.</p><textarea value={cancelReason} onChange={e=>setCancelReason(e.target.value)} placeholder="Justificativo obligatorio de la anulación..."/><div><button className="danger" onClick={cancelOrder}>CONFIRMAR ANULACIÓN</button><button onClick={()=>{setShowCancel(false);setCancelReason("")}}>CANCELAR</button></div></div></div>}
  {showHistory&&<div className="history-panel no-print"><div className="history-head"><b>HISTORIAL DEL CLIENTE — {client.nombre||client.ruc}</b><button onClick={resetHistory}>CERRAR</button></div>{history.map(o=><div className={`history-row ${o.status==="ANULADA"?"annulled":""}`} key={o.number}><span><b>N° {String(o.number).padStart(6,"0")}</b> · {fmtDate(o.date)} · {o.type}</span><span>{o.status}</span><span><b>{o.currency==="USD"?"US$":"Gs."} {money(o.total)}</b><button onClick={()=>loadOrder(o)}>CONSULTAR</button></span></div>)}</div>}
  <main className={`sheet ${status==="ANULADA"?"sheet-annulled":""}`}><header><div className="brand"><img src="/NOTA-DE-PEDIDO/logo-masfertil.svg" className="logo"/><div>Ruta PY 13 Km 181 CAAGUAZÚ - PARAGUAY<br/>Cel.: (0971) 436 458 / (0971) 406 595<br/>(0984) 854 327</div><strong>DISTRIBUIDOR DE FERTILIZANTES<br/>VENTA DE PRODUCTOS AGROPECUARIOS<br/>COMERCIO AL POR MAYOR<br/>DE PRODUCTOS QUÍMICOS INDUSTRIALES</strong></div><div className="title"><b>R.U.C. 80108603-5</b><b>NOTA DE PEDIDO</b><big>N° {String(number).padStart(6,"0")}</big>{status==="ANULADA"&&<em>ANULADA</em>}</div></header>
  <div className="types">{["RESERVA","PEDIDO","PRESUPUESTO"].map(t=><label key={t}><b>{t}</b><input type="checkbox" checked={type===t} disabled={locked} onChange={()=>setType(t)}/></label>)}</div>
  <div className="client">{[["Fecha:",date,setDate,"date"],["RUC/C.I.:",client.ruc,v=>{setC("ruc",v);setQuery(v)}],["Señor (es):",client.nombre,v=>setC("nombre",v)],["Área:",client.area,v=>setC("area",v)],["Dirección/ Región:",client.direccion,v=>setC("direccion",v)],["Teléfono:",client.telefono,v=>setC("telefono",v)],["Correo:",client.correo,v=>setC("correo",v)],["Ciudad:",client.ciudad,v=>setC("ciudad",v)]].map(([l,v,on,t],i)=><label className={`client-field field-${i+1}`} key={l}><b>{l}</b><input disabled={locked} type={t||"text"} value={v} onChange={e=>on(e.target.value)}/></label>)}</div>
  <section className="table"><div className="thead"><b>Cantidad</b><b>Unidad</b><b>Descripción de mercadería</b><b>Precio Unitario</b><b>Sub-total</b></div>{items.map((it,i)=><div className="tr" key={i}><input disabled={locked} value={it.cantidad} onChange={e=>update(i,"cantidad",e.target.value)}/><input disabled={locked} value={it.unidad} onChange={e=>update(i,"unidad",e.target.value)}/><input disabled={locked} value={it.descripcion} onChange={e=>update(i,"descripcion",e.target.value)}/><input disabled={locked} value={it.precio} onChange={e=>update(i,"precio",e.target.value)}/><span>{symbol} {money(Number(it.cantidad||0)*Number(it.precio||0))}</span></div>)}<div className="total"><b>Total de {currencyLabel} ({symbol})</b><strong>{symbol} {money(total)}</strong></div><div className="letters"><b>Total en<br/>letras ({symbol}):</b><span>{words(total,currency)}</span></div></section>
  <section className="obs" style={{"--obs-height":obsHeight}}><b>OBSERVACIONES:</b><textarea disabled={locked} value={obs} onChange={e=>setObs(e.target.value)} placeholder=""/></section><section className="conditions"><label><input disabled={locked} type="checkbox" checked={contado} onChange={e=>setContado(e.target.checked)}/> PAGO AL CONTADO</label><label><input disabled={locked} type="checkbox" checked={semilla} onChange={e=>setSemilla(e.target.checked)}/> TRATAMIENTO DE SEMILLA</label><label><input disabled={locked} type="checkbox" checked={plazo} onChange={e=>setPlazo(e.target.checked)}/> PAGO A PLAZO</label><label>Vencimiento: <input disabled={locked} type="date" value={venc} onChange={e=>setVenc(e.target.value)}/></label></section><section className="flete"><b>MODALIDAD DEL FLETE</b><label><input disabled={locked} type="checkbox" checked={flete==="cliente"} onChange={()=>setFlete("cliente")}/> ( ) Cliente Retira</label><label><input disabled={locked} type="checkbox" checked={flete==="masfertil"} onChange={()=>setFlete("masfertil")}/> ( ) MÁSFERTIL S.A.</label></section><footer><div><i></i><b>Firma del Vendedor</b><b>MÁSFERTIL S.A.</b><b>RUC: 80108603-5</b></div><div><i></i><b>Firma del Comprador/ Representante Legal</b></div><div className="seal"><i></i><b>Aclaración y/o Sello</b></div></footer></main>
 </div>
}
