import React, { useMemo, useState } from "react";

const CLIENT_KEY="masfertil_clientes_v1", ORDER_KEY="masfertil_pedidos_v1", NEXT_KEY="masfertil_numero_v1";
const blank=()=>({cantidad:"",unidad:"",descripcion:"",precio:""});
const emptyClient={ruc:"",nombre:"",area:"",direccion:"",region:"",telefono:"",correo:"",ciudad:""};
const money=v=>Number(v||0).toLocaleString("es-PY",{minimumFractionDigits:2,maximumFractionDigits:2});
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function words(n){const x=Math.round(Number(n||0)); const u=["CERO","UNO","DOS","TRES","CUATRO","CINCO","SEIS","SIETE","OCHO","NUEVE"]; return x<10?u[x]:`${x} DÓLARES AMERICANOS`;}
export default function App(){
 const [number,setNumber]=useState(()=>Math.max(51,Number(localStorage.getItem(NEXT_KEY)||51)));
 const [date,setDate]=useState(new Date().toISOString().slice(0,10)),[type,setType]=useState("PEDIDO");
 const [client,setClient]=useState(emptyClient),[query,setQuery]=useState("");
 const [items,setItems]=useState(()=>Array.from({length:10},blank)),[obs,setObs]=useState("");
 const [contado,setContado]=useState(false),[plazo,setPlazo]=useState(false),[semilla,setSemilla]=useState(false),[venc,setVenc]=useState(""),[flete,setFlete]=useState(""); const [msg,setMsg]=useState("");
 const total=useMemo(()=>items.reduce((s,i)=>s+Number(i.cantidad||0)*Number(i.precio||0),0),[items]);
 const setC=(k,v)=>setClient(c=>({...c,[k]:v}));
 const update=(i,k,v)=>setItems(a=>a.map((x,j)=>j===i?{...x,[k]:v}:x));
 function buscar(){const k=query.trim().replace(/\s/g,"");const c=load(CLIENT_KEY,{});if(c[k]){setClient(c[k]);setMsg("Cliente encontrado.")}else{setClient({...emptyClient,ruc:query});setMsg("Cliente no encontrado. Puede registrarlo.")}}
 function saveClient(){if(!client.ruc.trim())return setMsg("Ingrese RUC/C.I.");const c=load(CLIENT_KEY,{});c[client.ruc.trim().replace(/\s/g,"")]=client;localStorage.setItem(CLIENT_KEY,JSON.stringify(c));setMsg("Cliente guardado.")}
 function save(){if(!client.ruc.trim())return setMsg("Ingrese RUC/C.I.");const o=load(ORDER_KEY,[]);o.push({number,date,type,client,items,total,obs,contado,plazo,semilla,venc,flete});localStorage.setItem(ORDER_KEY,JSON.stringify(o));const c=load(CLIENT_KEY,{});c[client.ruc.trim().replace(/\s/g,"")]=client;localStorage.setItem(CLIENT_KEY,JSON.stringify(c));const next=number+1;localStorage.setItem(NEXT_KEY,next);setNumber(next);setMsg(`Guardada N° ${String(number).padStart(6,"0")}. Nueva N° ${String(next).padStart(6,"0")}.`)}
 function nuevo(){setNumber(Math.max(51,Number(localStorage.getItem(NEXT_KEY)||51)));setDate(new Date().toISOString().slice(0,10));setType("PEDIDO");setClient(emptyClient);setQuery("");setItems(Array.from({length:10},blank));setObs("");setContado(false);setPlazo(false);setSemilla(false);setVenc("");setFlete("");setMsg("")}
 return <div className="app"><div className="toolbar no-print"><button onClick={save}>GUARDAR NOTA</button><button onClick={saveClient}>GUARDAR CLIENTE</button><button onClick={()=>print()}>IMPRIMIR</button><button onClick={nuevo}>NUEVA NOTA</button><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Consultar RUC/C.I."/><button onClick={buscar}>BUSCAR</button></div>{msg&&<span>{msg}</span>}</div>
 <main className="sheet"><header><div className="brand"><img src="/NOTA-DE-PEDIDO/logo-masfertil.svg" className="logo"/><div>Ruta PY 13 Km 181 CAAGUAZÚ - PARAGUAY<br/>Cel.: (0971) 436 458 / (0971) 406 595<br/>(0984) 854 327</div><strong>DISTRIBUIDOR DE FERTILIZANTES<br/>VENTA DE PRODUCTOS AGROPECUARIOS<br/>COMERCIO AL POR MAYOR<br/>DE PRODUCTOS QUÍMICOS INDUSTRIALES</strong></div><div className="title"><b>R.U.C. 80108603-5</b><b>NOTA DE PEDIDO</b><big>N° {String(number).padStart(6,"0")}</big></div></header>
 <div className="types">{["RESERVA","PEDIDO","PRESUPUESTO"].map(t=><label key={t}><b>{t}</b><input type="checkbox" checked={type===t} onChange={()=>setType(t)}/></label>)}</div>
 <div className="client">{[["Fecha:",date,setDate,"date"],["RUC/C.I.:",client.ruc,v=>{setC("ruc",v);setQuery(v)}],["Señor (es):",client.nombre,v=>setC("nombre",v)],["Área:",client.area,v=>setC("area",v)],["Dirección/ Región:",client.direccion,v=>setC("direccion",v)],["Teléfono:",client.telefono,v=>setC("telefono",v)],["Correo:",client.correo,v=>setC("correo",v)],["Ciudad:",client.ciudad,v=>setC("ciudad",v)]].map(([l,v,on,t])=><label key={l}><b>{l}</b><input type={t||"text"} value={v} onChange={e=>on(e.target.value)}/></label>)}</div>
 <section className="table"><div className="thead"><b>Cantidad</b><b>Unidad</b><b>Descripción de mercadería</b><b>Precio Unitario</b><b>Sub-total</b></div>{items.map((it,i)=><div className="tr" key={i}><input value={it.cantidad} onChange={e=>update(i,"cantidad",e.target.value)}/><input value={it.unidad} onChange={e=>update(i,"unidad",e.target.value)}/><input value={it.descripcion} onChange={e=>update(i,"descripcion",e.target.value)}/><input value={it.precio} onChange={e=>update(i,"precio",e.target.value)}/><span>$ {money(Number(it.cantidad||0)*Number(it.precio||0))}</span></div>)}<div className="total"><b>Total de Dólares americanos (U$)</b><strong>$ {money(total)}</strong></div><div className="letters"><b>Total en<br/>letras (U$):</b><span>{words(total)}</span></div></section>
 <section className="obs"><b>OBSERVACIONES:</b><textarea value={obs} onChange={e=>setObs(e.target.value)}/></section><section className="conditions"><label><input type="checkbox" checked={contado} onChange={e=>setContado(e.target.checked)}/> PAGO AL CONTADO</label><label><input type="checkbox" checked={semilla} onChange={e=>setSemilla(e.target.checked)}/> TRATAMIENTO DE SEMILLA</label><label><input type="checkbox" checked={plazo} onChange={e=>setPlazo(e.target.checked)}/> PAGO A PLAZO</label><label>Vencimiento: <input type="date" value={venc} onChange={e=>setVenc(e.target.value)}/></label></section><section className="flete"><b>MODALIDAD DEL FLETE</b><label><input type="checkbox" checked={flete==="cliente"} onChange={()=>setFlete("cliente")}/> ( ) Cliente Retira</label><label><input type="checkbox" checked={flete==="masfertil"} onChange={()=>setFlete("masfertil")}/> ( ) MÁSFERTIL S.A.</label></section><footer><div><i></i><b>Firma del Vendedor</b><b>MÁSFERTIL S.A.</b><b>RUC: 80108603-5</b></div><div><i></i><b>Firma del Comprador/ Representante Legal</b></div><div className="seal"><i></i><b>Aclaración y/o Sello</b></div></footer></main></div>
}